# Generated by Django 6.0.5 on 2026-05-07 20:02

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Specialization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='CaregiverProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('bio', models.TextField(blank=True)),
                ('experience', models.CharField(choices=[('junior', 'Junior (0-2 yrs)'), ('mid', 'Mid (2-5 yrs)'), ('senior', 'Senior (5+ yrs)')], default='junior', max_length=20)),
                ('hourly_rate', models.DecimalField(decimal_places=2, default=500, max_digits=8)),
                ('years_exp', models.PositiveIntegerField(default=0)),
                ('id_number', models.CharField(blank=True, max_length=20)),
                ('certificate', models.FileField(blank=True, null=True, upload_to='certificates/')),
                ('is_available', models.BooleanField(default=True)),
                ('rating_avg', models.DecimalField(decimal_places=2, default=0.0, max_digits=3)),
                ('rating_count', models.PositiveIntegerField(default=0)),
                ('location_name', models.CharField(blank=True, max_length=200)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='caregiver_profile', to=settings.AUTH_USER_MODEL)),
                ('specializations', models.ManyToManyField(blank=True, to='caregivers.specialization')),
            ],
            options={
                'ordering': ['-rating_avg'],
            },
        ),
        migrations.CreateModel(
            name='Availability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.IntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')])),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('caregiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availability', to='caregivers.caregiverprofile')),
            ],
            options={
                'ordering': ['day'],
                'unique_together': {('caregiver', 'day')},
            },
        ),
    ]
